# Generated by Django 5.1.15 on 2026-04-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_rename_pv_processing_status_idx_products_pr_process_a49781_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان (داخلی)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن alt')),
                ('position', models.CharField(choices=[('top', 'بالای محصولات'), ('middle', 'وسط صفحه'), ('bottom', 'پایین صفحه')], default='top', max_length=10, verbose_name='موقعیت')),
                ('width', models.CharField(choices=[('full', 'تمام\u200cعرض'), ('half', 'نیمه')], default='full', max_length=10, verbose_name='عرض')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='شروع نمایش')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='پایان نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه')),
                ('button_link', models.CharField(blank=True, max_length=500, verbose_name='لینک دکمه')),
                ('image_desktop', models.ImageField(upload_to='sliders/', verbose_name='تصویر دسکتاپ (1920×600)')),
                ('image_mobile', models.ImageField(blank=True, help_text='خالی = همان دسکتاپ', null=True, upload_to='sliders/', verbose_name='تصویر موبایل (768×400)')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ متن')),
                ('overlay_opacity', models.IntegerField(default=30, help_text='0=شفاف، 100=کاملاً تاریک', verbose_name='تاریکی پس\u200cزمینه (%)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع نمایش')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر صفحه اصلی',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بخش')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('icon', models.CharField(blank=True, help_text='مثال: bi-fire, bi-star-fill, bi-lightning', max_length=50, verbose_name='آیکون Bootstrap')),
                ('section_type', models.CharField(choices=[('product_auto', 'محصولات خودکار'), ('product_manual', 'محصولات دستی'), ('html_custom', 'کد HTML سفارشی'), ('blog_posts', 'آخرین مقالات'), ('brands', 'لوگوی شرکت\u200cها')], max_length=20, verbose_name='نوع بخش')),
                ('auto_filter', models.CharField(blank=True, choices=[('newest', 'جدیدترین'), ('featured', 'ویژه'), ('popular', 'پربازدید'), ('cheapest', 'ارزان\u200cترین')], default='newest', max_length=20, verbose_name='فیلتر خودکار')),
                ('auto_comb', models.IntegerField(blank=True, help_text='خالی = همه شانه\u200cها', null=True, verbose_name='فیلتر شانه')),
                ('html_content', models.TextField(blank=True, verbose_name='کد HTML')),
                ('item_count', models.IntegerField(default=8, verbose_name='تعداد آیتم')),
                ('bg_color', models.CharField(blank=True, help_text='خالی = شفاف. مثال: #F5F5F5', max_length=7, verbose_name='رنگ پس\u200cزمینه')),
                ('show_more_link', models.CharField(blank=True, max_length=500, verbose_name='لینک «مشاهده بیشتر»')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='محصولات انتخابی')),
            ],
            options={
                'verbose_name': 'بخش صفحه اصلی',
                'verbose_name_plural': 'بخش\u200cهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
    ]
