# Generated by Django 5.1.15 on 2026-04-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('saman', 'سامان'), ('mellat', 'ملت'), ('parsian', 'پارسیان')], max_length=50, unique=True, verbose_name='نام درگاه')),
                ('merchant_id', models.CharField(max_length=100, verbose_name='شناسه پذیرنده')),
                ('terminal_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه ترمینال')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='کلید API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='حالت تست')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه\u200cهای پرداخت',
                'db_table': 'payment_gateways',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('check', 'چک صیادی'), ('beta', 'طرح بتا (بانک رفاه)')], max_length=20, verbose_name='نوع طرح')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل فاکتور')),
                ('down_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='پیش\u200cپرداخت')),
                ('financed_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ قابل اقساط')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نرخ سود ماهانه (%)')),
                ('total_interest', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مجموع سود')),
                ('total_with_interest', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل با سود')),
                ('num_installments', models.PositiveIntegerField(verbose_name='تعداد اقساط')),
                ('period', models.CharField(choices=[('monthly', 'ماهانه'), ('bimonthly', 'دوماهانه')], default='monthly', max_length=20, verbose_name='دوره پرداخت')),
                ('installment_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ هر قسط')),
                ('first_due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید اول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_installments', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'طرح اقساط',
                'verbose_name_plural': 'طرح\u200cهای اقساط',
                'db_table': 'installment_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)')),
                ('tracking_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد پیگیری سیستم')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسه تراکنش درگاه')),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شماره مرجع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('completed', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('refunded', 'برگشت داده شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentgateway', verbose_name='درگاه پرداخت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='شماره قسط')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ قسط')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('pending', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('overdue', 'سررسید گذشته'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='شماره چک')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.installmentplan', verbose_name='طرح اقساط')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='payments.transaction', verbose_name='تراکنش')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'db_table': 'installments',
                'ordering': ['plan', 'installment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at', 'status'], name='transaction_created_6450cb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', '-created_at'], name='transaction_order_i_2ea2e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('plan', 'installment_number')},
        ),
    ]
