# Generated by Django 5.1.15 on 2026-04-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کاتالوگ')),
                ('unique_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='کد یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to=settings.AUTH_USER_MODEL, verbose_name='ایجادشده توسط')),
                ('products', models.ManyToManyField(related_name='in_catalogs', to='products.product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'کاتالوگ',
                'verbose_name_plural': 'کاتالوگ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
