# Generated by Django 5.1.15 on 2026-04-11 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید با 09 شروع شود و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره موبایل')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام (اختیاری)')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('unsubscribed', 'لغو عضویت')], default='active', max_length=15, verbose_name='وضعیت')),
                ('source', models.CharField(choices=[('footer', 'فرم فوتر'), ('popup', 'پاپ\u200cآپ'), ('manual', 'افزودن دستی'), ('import', 'واردکردن فایل')], default='footer', max_length=10, verbose_name='منبع عضویت')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سایت')),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کمپین')),
                ('message', models.TextField(help_text='متغیرها: {name} نام مشترک، {site_name} نام سایت', verbose_name='متن پیامک')),
                ('recipient_type', models.CharField(choices=[('all_active', 'همه مشترکین فعال'), ('selected', 'انتخابی'), ('site_users', 'مشتریان سایت')], default='all_active', max_length=15, verbose_name='گیرندگان')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sending', 'در حال ارسال'), ('completed', 'تکمیل\u200cشده'), ('cancelled', 'لغو\u200cشده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='تعداد گیرندگان')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='ارسال\u200cشده')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='ناموفق')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='خالی = ارسال فوری', null=True, verbose_name='زمان\u200cبندی ارسال')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'کمپین پیامکی',
                'verbose_name_plural': 'کمپین\u200cهای پیامکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره')),
                ('status', models.CharField(choices=[('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], max_length=10, verbose_name='وضعیت')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newsletter.smscampaign', verbose_name='کمپین')),
            ],
            options={
                'verbose_name': 'لاگ کمپین',
                'verbose_name_plural': 'لاگ\u200cهای کمپین',
                'ordering': ['-sent_at'],
            },
        ),
    ]
