# Generated by Django 5.1.15 on 2026-04-10 20:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_seed_default_data'),
        ('orders', '0001_initial'),
        ('products', '0006_rename_pv_processing_status_idx_products_pr_process_a49781_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='حروف انگلیسی و اعداد. مثال: SUMMER1405', max_length=30, unique=True, verbose_name='کد تخفیف')),
                ('coupon_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغی (تومان)')], max_length=10, verbose_name='نوع تخفیف')),
                ('amount', models.BigIntegerField(help_text='درصدی: عدد 1-100 / مبلغی: مبلغ به تومان', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مقدار تخفیف')),
                ('max_discount', models.BigIntegerField(blank=True, help_text='فقط برای نوع درصدی. خالی = بدون سقف', null=True, verbose_name='سقف تخفیف (تومان)')),
                ('min_order_amount', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مبلغ سفارش (تومان)')),
                ('max_usage_total', models.PositiveIntegerField(default=0, help_text='0 = بدون محدودیت', verbose_name='حداکثر استفاده کل')),
                ('max_usage_per_user', models.PositiveIntegerField(default=1, help_text='0 = بدون محدودیت', verbose_name='حداکثر استفاده هر کاربر')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات (داخلی)')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('limited_to_categories', models.ManyToManyField(blank=True, help_text='خالی = همه دسته\u200cبندی\u200cها', to='catalog.designtype', verbose_name='محدود به دسته\u200cبندی (نوع طرح)')),
                ('limited_to_products', models.ManyToManyField(blank=True, help_text='خالی = همه محصولات', to='products.product', verbose_name='محدود به محصولات')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.BigIntegerField(verbose_name='مبلغ تخفیف اعمال\u200cشده')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon', verbose_name='کوپن')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کوپن',
                'verbose_name_plural': 'لاگ استفاده کوپن\u200cها',
                'ordering': ['-used_at'],
            },
        ),
    ]
