# Generated by Django 5.1.15 on 2026-04-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/categories/', verbose_name='تصویر')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیحات SEO')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقالات',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقالات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(blank=True, verbose_name='محتوا (HTML)')),
                ('excerpt', models.TextField(blank=True, help_text='نمایش در لیست مقالات و meta description', verbose_name='خلاصه')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/featured/', verbose_name='تصویر شاخص')),
                ('page_type', models.CharField(choices=[('page', 'صفحه ایستا'), ('post', 'مقاله / بلاگ'), ('guide', 'راهنما')], default='page', max_length=10, verbose_name='نوع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده'), ('archived', 'آرشیو')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('show_in_header', models.BooleanField(default=False, verbose_name='نمایش در فهرست هدر')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='نمایش در فهرست فوتر')),
                ('menu_order', models.IntegerField(default=0, verbose_name='ترتیب در فهرست')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('seo_title', models.CharField(blank=True, help_text='خالی = عنوان صفحه', max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, help_text='خالی = خلاصه', verbose_name='توضیحات SEO')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, help_text='فقط برای مقالات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.postcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'صفحه / مقاله',
                'verbose_name_plural': 'صفحات و مقالات',
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'page_type'], name='pages_page_status_6a7e0d_idx'), models.Index(fields=['slug'], name='pages_page_slug_3e99a9_idx')],
            },
        ),
    ]
