# Generated by Django 5.1.15 on 2026-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/%Y/%m/', verbose_name='فایل پیوست'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('voice', 'ویس'), ('file', 'فایل')], default='text', max_length=10, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='متن پیام'),
        ),
    ]
