# Generated by Django 5.1.15 on 2026-04-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/manufacturers/', verbose_name='لوگو')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیحات SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت تولیدی',
                'verbose_name_plural': 'شرکت\u200cهای تولیدی',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام آلبوم')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, verbose_name='اسلاگ')),
                ('comb', models.PositiveIntegerField(choices=[(700, '۷۰۰ شانه'), (1000, '۱۰۰۰ شانه'), (1200, '۱۲۰۰ شانه'), (1500, '۱۵۰۰ شانه')], verbose_name='شانه')),
                ('density', models.PositiveIntegerField(blank=True, null=True, verbose_name='تراکم')),
                ('yarn_type', models.CharField(choices=[('acrylic', 'آکرلیک'), ('polyester', 'پلی\u200cاستر'), ('bcf', 'BCF'), ('heat_set', 'هیت\u200cست'), ('other', 'سایر')], default='acrylic', max_length=20, verbose_name='جنس نخ')),
                ('weight_class', models.CharField(choices=[('light', 'سبک'), ('heavy', 'سنگین'), ('medium', 'متوسط')], default='heavy', max_length=20, verbose_name='وزن')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('nine_m_waste_type', models.CharField(choices=[('fixed', 'عدد ثابت (تومان)'), ('percent', 'درصدی')], default='fixed', max_length=10, verbose_name='نوع پرتی ۹ متری')),
                ('nine_m_waste_value', models.DecimalField(decimal_places=2, default=0, help_text='برای ثابت: مبلغ به تومان / برای درصدی: عدد درصد (مثلاً 10)', max_digits=15, verbose_name='مقدار پرتی')),
                ('base_price_12m', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت خرید پایه ۱۲ متری (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیحات SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.manufacturer', verbose_name='شرکت تولیدی')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم\u200cها',
                'ordering': ['manufacturer', 'sort_order', 'name'],
                'unique_together': {('manufacturer', 'slug')},
            },
        ),
    ]
