# Generated by Django 5.1.15 on 2026-04-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام رنگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('color_code', models.CharField(blank=True, help_text='مثال: #1A237E', max_length=7, verbose_name='کد رنگ HEX')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رنگ زمینه',
                'verbose_name_plural': 'رنگ\u200cهای زمینه',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarpetSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سایز')),
                ('size_type', models.CharField(choices=[('rectangular', 'مستطیل / مربع'), ('round', 'گرد'), ('runner', 'کناره'), ('doormat', 'پادری'), ('cushion', 'رویه پشتی')], default='rectangular', max_length=20, verbose_name='نوع سایز')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='طول (متر)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عرض (متر)')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='قطر (متر) - فقط برای گرد')),
                ('area', models.DecimalField(decimal_places=4, help_text='برای مستطیل: طول×عرض / برای گرد: π×(قطر/2)²', max_digits=10, verbose_name='مساحت (متر مربع)')),
                ('is_nine_meter', models.BooleanField(default=False, help_text='اگر بله، قیمت با فرمول پرتی محاسبه می\u200cشود', verbose_name='سایز ۹ متری (۳.۵۰×۲.۵۰)')),
                ('default_order_rule', models.CharField(choices=[('any', 'آزاد (هر تعداد)'), ('even', 'فقط زوج (جفتی)')], default='any', max_length=10, verbose_name='قانون سفارش پیش\u200cفرض')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سایز فرش',
                'verbose_name_plural': 'سایزهای فرش',
                'ordering': ['sort_order', '-area'],
            },
        ),
        migrations.CreateModel(
            name='ColorTone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='تناژ رنگ')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تناژ رنگ',
                'verbose_name_plural': 'تناژهای رنگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام طرح')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیح SEO')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع طرح',
                'verbose_name_plural': 'انواع طرح',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ویژگی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع بافت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع بافت',
                'verbose_name_plural': 'انواع بافت',
                'ordering': ['name'],
            },
        ),
    ]
