# Generated by Django 5.1.15 on 2026-04-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ویجت')),
                ('widget_type', models.CharField(choices=[('links', 'لیست لینک\u200cها'), ('text', 'متن ساده'), ('html', 'کد HTML سفارشی'), ('social', 'شبکه\u200cهای اجتماعی'), ('contact', 'اطلاعات تماس')], max_length=10, verbose_name='نوع')),
                ('content', models.TextField(blank=True, help_text='برای «متن»: متن ساده. برای «HTML»: کد HTML (نماد اعتماد، ساماندهی و...)', verbose_name='محتوا')),
                ('column', models.IntegerField(default=1, help_text='شماره ستون فوتر از راست', verbose_name='ستون (1-4)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویجت فوتر',
                'verbose_name_plural': 'ویجت\u200cهای فوتر',
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('link', models.CharField(blank=True, help_text='مثال: /farsh/ یا /page/about-us/ یا https://...', max_length=500, verbose_name='لینک')),
                ('icon', models.CharField(blank=True, help_text='مثال: bi-house, bi-telephone, bi-cart3', max_length=50, verbose_name='آیکون Bootstrap')),
                ('position', models.CharField(choices=[('header', 'فهرست هدر'), ('footer', 'فهرست فوتر'), ('both', 'هدر و فوتر')], default='header', max_length=10, verbose_name='موقعیت')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('target_blank', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='کلاس CSS اضافی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appearance.menuitem', verbose_name='والد (زیرمنو)')),
            ],
            options={
                'verbose_name': 'آیتم فهرست',
                'verbose_name_plural': 'آیتم\u200cهای فهرست',
                'ordering': ['position', 'order'],
            },
        ),
    ]
