# Generated by Django 5.1.15 on 2026-04-09 04:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_seed_default_data'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('reviewing', 'در حال بررسی'), ('confirmed', 'تأیید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_method', models.CharField(choices=[('online_full', 'نقدی آنلاین کامل'), ('deposit_on_delivery', 'بیعانه + پرداخت موقع تحویل'), ('installment_check', 'اقساطی چکی'), ('installment_beta', 'اقساطی بتا')], max_length=30, verbose_name='روش پرداخت')),
                ('total_amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ کل')),
                ('deposit_amount', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بیعانه')),
                ('paid_amount', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت شده')),
                ('shipping_cost', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='هزینه ارسال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('is_price_today', models.BooleanField(default=False, verbose_name='قیمت روز تحویل')),
                ('final_price_at_delivery', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت نهایی موقع تحویل')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='ارسال رایگان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.address', verbose_name='آدرس ارسال')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom_size', models.BooleanField(default=False, verbose_name='سایز سفارشی')),
                ('custom_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='طول سفارشی (متر)')),
                ('custom_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عرض سفارشی (متر)')),
                ('custom_price_per_sqm', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت هر مترمربع (سفارشی)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('is_pair_order', models.BooleanField(default=False, verbose_name='سفارش زوجی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.carpetsize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'لاگ وضعیت',
                'verbose_name_plural': 'لاگ\u200cهای وضعیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
