# Generated by Django 5.1.15 on 2026-04-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='همیار فرش', max_length=200, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='لوگو سایت (PNG)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='فاویکون')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن ثابت')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساپ')),
                ('telegram_id', models.CharField(blank=True, max_length=100, verbose_name='آی\u200cدی تلگرام')),
                ('instagram_id', models.CharField(blank=True, max_length=100, verbose_name='آی\u200cدی اینستاگرام')),
                ('eitaa_id', models.CharField(blank=True, max_length=100, verbose_name='آی\u200cدی ایتا')),
                ('bale_id', models.CharField(blank=True, max_length=100, verbose_name='آی\u200cدی بله')),
                ('website_url', models.URLField(blank=True, verbose_name='آدرس سایت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس فیزیکی')),
                ('thumbnail_width', models.PositiveIntegerField(default=350, verbose_name='عرض تامبنیل (پیکسل)')),
                ('thumbnail_height', models.PositiveIntegerField(default=350, verbose_name='ارتفاع تامبنیل (پیکسل)')),
                ('featured_image_size', models.PositiveIntegerField(default=1000, verbose_name='سایز تصویر شاخص (پیکسل)')),
                ('info_bar_color', models.CharField(default='#C62828', max_length=7, verbose_name='رنگ نوار اطلاعات تصویر شاخص')),
                ('profit_percent', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='درصد سود فروش')),
                ('shipping_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه حمل و نقل (تومان)')),
                ('rounding_step', models.PositiveBigIntegerField(default=100000, verbose_name='گرد کردن قیمت به بالا (تومان)')),
                ('free_shipping_min', models.PositiveBigIntegerField(default=25000000, verbose_name='حداقل مبلغ ارسال رایگان (تومان)')),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='درصد بیعانه')),
                ('cancellation_fee_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='درصد جریمه انصراف از بیعانه')),
                ('installment_max', models.PositiveBigIntegerField(default=75000000, verbose_name='سقف فروش اقساطی (تومان)')),
                ('check_max_months', models.PositiveIntegerField(default=12, verbose_name='حداکثر ماه\u200cهای چکی')),
                ('beta_max_months', models.PositiveIntegerField(default=18, verbose_name='حداکثر ماه\u200cهای بتا')),
                ('check_monthly_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='سود ماهانه چکی ماه\u200cبه\u200cماه (%)')),
                ('check_bimonthly_rate', models.DecimalField(decimal_places=2, default=2.7, max_digits=5, verbose_name='سود ماهانه چکی دوماه\u200cبه\u200cدوماه (%)')),
                ('beta_monthly_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='سود ماهانه بتا (%)')),
                ('check_prepay_required', models.BooleanField(default=False, verbose_name='پیش\u200cپرداخت چکی الزامی؟')),
                ('beta_prepay_required', models.BooleanField(default=False, verbose_name='پیش\u200cپرداخت بتا الزامی؟')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO سایت')),
                ('seo_description', models.TextField(blank=True, verbose_name='توضیحات SEO سایت')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='کلمات کلیدی SEO')),
                ('product_desc_template', models.TextField(blank=True, help_text='متغیرها: {name}, {color}, {comb}, {density}, {yarn}, {design}, {weave}, {price_12m}', verbose_name='قالب شرح خودکار محصول')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
