# Generated by Django 5.1.15 on 2026-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='beta_monthly_rate',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='check_bimonthly_rate',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='check_monthly_rate',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='beta_monthly_interest_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='نرخ سود ماهانه طرح بتا (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='check_monthly_interest_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='نرخ سود ماهانه چک صیادی (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='beta_max_months',
            field=models.PositiveIntegerField(default=18, verbose_name='حداکثر ماه\u200cهای طرح بتا'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='check_max_months',
            field=models.PositiveIntegerField(default=12, verbose_name='حداکثر ماه\u200cهای چک صیادی'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='check_prepay_required',
            field=models.BooleanField(default=False, verbose_name='پیش\u200cپرداخت چک صیادی الزامی؟'),
        ),
    ]
