# Generated by Django 5.1.15 on 2026-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_remove_sitesettings_beta_monthly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='کلید API سرویس پیامک'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال\u200cسازی ارسال پیامک'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_on_confirm',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک هنگام تأیید سفارش'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_on_delivered',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک هنگام تحویل سفارش'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_on_order',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک هنگام ثبت سفارش'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_on_shipped',
            field=models.BooleanField(default=False, verbose_name='ارسال پیامک هنگام ارسال سفارش'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sms_sender',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره فرستنده'),
        ),
    ]
