# Generated by Django 5.1.15 on 2026-04-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_sitesettings_sms_api_key_sitesettings_sms_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_body_end',
            field=models.TextField(blank=True, help_text='چت آنلاین، اسکریپت سفارشی', verbose_name='کد قبل از </body>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_body_start',
            field=models.TextField(blank=True, help_text='گوگل تگ منیجر (noscript)', verbose_name='کد بعد از <body>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_footer_code',
            field=models.TextField(blank=True, help_text='نماد اعتماد الکترونیکی، ساماندهی', verbose_name='کد HTML انتهای فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_head_code',
            field=models.TextField(blank=True, help_text='گوگل آنالیتیکس، فونت خارجی، CSS اضافی', verbose_name='کد سفارشی <head>'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(default='#212121', max_length=7, verbose_name='رنگ پس\u200cزمینه فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_bg_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ پس\u200cزمینه هدر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#C62828', max_length=7, verbose_name='رنگ اصلی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#1565C0', max_length=7, verbose_name='رنگ ثانویه'),
        ),
    ]
