# Generated by Django 5.1.15 on 2026-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_sitesettings_custom_body_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_enabled',
            field=models.BooleanField(default=True, verbose_name='فرم خبرنامه در فوتر فعال باشد؟'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_text',
            field=models.CharField(blank=True, default='جهت اطلاع از فروش\u200cهای ویژه و تخفیف\u200cها شماره موبایل خود را وارد کنید', max_length=500, verbose_name='متن توضیحی خبرنامه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_title',
            field=models.CharField(default='خبرنامه', max_length=200, verbose_name='عنوان بخش خبرنامه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='newsletter_welcome_sms',
            field=models.TextField(blank=True, default='{name} عزیز، خوش آمدید!\nاز عضویت شما در خبرنامه {site_name} متشکریم.\nبرای اطلاع از تخفیف\u200cها و محصولات جدید با ما همراه باشید.', help_text='متغیرها: {name}, {site_name}', verbose_name='متن پیامک خوش\u200cآمدگویی'),
        ),
    ]
