# Generated by Django 5.1.15 on 2026-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_sitesettings_newsletter_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='live_chat_enabled',
            field=models.BooleanField(default=True, verbose_name='چت داخلی فعال باشد؟'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='live_chat_external_code',
            field=models.TextField(blank=True, help_text='کد embed سرویس خارجی (Raychat/Goftino/Crisp). اگر پر باشد به\u200cجای چت داخلی استفاده می\u200cشود.', verbose_name='کد چت خارجی'),
        ),
    ]
