# Generated by Django 5.1.15 on 2026-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_sitesettings_live_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='featured_line1_template',
            field=models.CharField(blank=True, default='نقشه {name} | رنگ {color} | {comb} شانه | تراکم {density}', help_text='متغیرها: {name}, {color}, {comb}, {density}, {design}, {weave}, {feature}, {company}, {album}', max_length=500, verbose_name='خط ۱ نوار تصویر شاخص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_line2_template',
            field=models.CharField(blank=True, default='{company} | جنس نخ: {yarn} | {weave}', help_text='متغیرها: {name}, {color}, {comb}, {density}, {design}, {weave}, {feature}, {company}, {album}, {yarn}', max_length=500, verbose_name='خط ۲ نوار تصویر شاخص'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='featured_line3_template',
            field=models.CharField(blank=True, default='{mobile}  •  {website}', help_text='متغیرها: {mobile}, {phone}, {website}, {site_name}, {telegram}, {instagram}', max_length=500, verbose_name='خط ۳ نوار تصویر شاخص'),
        ),
    ]
