# Generated by Django 5.1.15 on 2026-04-10 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن اعلان')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک (اختیاری)')),
                ('link_text', models.CharField(blank=True, help_text='مثال: مشاهده جزئیات', max_length=100, verbose_name='متن لینک')),
                ('bg_color', models.CharField(default='#C62828', max_length=7, verbose_name='رنگ پس\u200cزمینه')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='رنگ متن')),
                ('icon', models.CharField(blank=True, help_text='مثال: bi-megaphone, bi-percent, bi-gift', max_length=50, verbose_name='آیکون')),
                ('dismissible', models.BooleanField(default=True, verbose_name='قابل بستن توسط کاربر')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'نوار اعلان\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره')),
                ('message', models.TextField(verbose_name='متن پیامک')),
                ('event', models.CharField(blank=True, max_length=30, verbose_name='رویداد')),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('api_response', models.TextField(blank=True, verbose_name='پاسخ API')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ پیامک\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('order_created', 'ثبت سفارش جدید (به مشتری)'), ('order_created_admin', 'ثبت سفارش جدید (به مدیر)'), ('order_confirmed', 'تأیید سفارش'), ('order_shipped', 'ارسال سفارش'), ('order_delivered', 'تحویل سفارش'), ('payment_success', 'پرداخت موفق'), ('installment_due', 'یادآوری قسط')], max_length=30, unique=True, verbose_name='رویداد')),
                ('template', models.TextField(help_text='متغیرها: {name}, {order_id}, {amount}, {site_name}, {status}', verbose_name='قالب پیامک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('notif_type', models.CharField(choices=[('order', 'سفارش'), ('payment', 'پرداخت'), ('system', 'سیستمی'), ('discount', 'تخفیف'), ('info', 'اطلاع\u200cرسانی')], default='info', max_length=15, verbose_name='نوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاع\u200cرسانی',
                'verbose_name_plural': 'اطلاع\u200cرسانی\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
