# Generated by Django 5.1.15 on 2026-04-08 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_seed_default_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام نقشه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='اسلاگ')),
                ('purchase_price_12m', models.PositiveBigIntegerField(blank=True, help_text='خالی باشد = از قیمت آلبوم استفاده می\u200cشود', null=True, verbose_name='قیمت خرید ۱۲ متری (تومان)')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود'), ('exhibition', 'نمایشگاهی'), ('coming_soon', 'به\u200cزودی')], default='available', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('seo_title', models.CharField(blank=True, help_text='خالی = تولید خودکار', max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.TextField(blank=True, help_text='خالی = تولید خودکار', verbose_name='توضیحات SEO')),
                ('description', models.TextField(blank=True, help_text='خالی = شرح خودکار استفاده می\u200cشود', verbose_name='شرح محصول (دستی)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.album', verbose_name='آلبوم')),
                ('background_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.backgroundcolor', verbose_name='رنگ زمینه')),
                ('color_tone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.colortone', verbose_name='تناژ رنگ')),
                ('design_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.designtype', verbose_name='نوع طرح')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.feature', verbose_name='ویژگی')),
                ('weave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.weavetype', verbose_name='نوع بافت')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='products/originals/', verbose_name='تصویر اصلی')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/', verbose_name='تامبنیل')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='products/featured/', verbose_name='تصویر شاخص 1000×1000')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر شاخص؟')),
                ('alt_text', models.CharField(blank=True, help_text='خالی = تولید خودکار از نام محصول', max_length=300, verbose_name='متن جایگزین (SEO)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='۱ تا ۵ ستاره', verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز محصول',
                'verbose_name_plural': 'امتیازات محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductSizeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_rule', models.CharField(choices=[('any', 'آزاد (هر تعداد)'), ('even', 'فقط زوج (جفتی)')], max_length=10, verbose_name='قانون سفارش')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_rules', to='products.product', verbose_name='محصول')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carpetsize', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'قانون سایز محصول',
                'verbose_name_plural': 'قوانین سایز محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='products/videos/', verbose_name='فایل ویدیو')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویدیو محصول',
                'verbose_name_plural': 'ویدیوهای محصول',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['album'], name='products_pr_album_i_ff265d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['background_color'], name='products_pr_backgro_93f3b0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['design_type'], name='products_pr_design__02f2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['avg_rating'], name='products_pr_avg_rat_3f90c0_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['product', 'status'], name='products_pr_product_34fff9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='productsizerule',
            unique_together={('product', 'size')},
        ),
    ]
