# Generated by Django 5.1.15 on 2026-04-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_default_data'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'امتیاز محصول', 'verbose_name_plural': 'امتیازات محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productsizerule',
            options={'verbose_name': 'قانون سفارش سایز', 'verbose_name_plural': 'قوانین سفارش سایزها'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['order', 'uploaded_at'], 'verbose_name': 'ویدیوی محصول', 'verbose_name_plural': 'ویدیوهای محصولات'},
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_product_1b7905_idx',
        ),
        migrations.RemoveIndex(
            model_name='productrating',
            name='products_pr_product_34fff9_idx',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='productsizerule',
            old_name='size',
            new_name='carpet_size',
        ),
        migrations.RenameField(
            model_name='productvideo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
        migrations.AlterUniqueTogether(
            name='productsizerule',
            unique_together={('product', 'carpet_size')},
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین (alt)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], verbose_name='امتیاز (1-5)'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productsizerule',
            name='order_rule',
            field=models.CharField(choices=[('free', 'آزاد'), ('even', 'فقط زوج')], max_length=10, verbose_name='قانون سفارش'),
        ),
        migrations.RemoveField(
            model_name='productsizerule',
            name='is_available',
        ),
    ]
