# Generated by Django 5.1.15 on 2026-04-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_design_type_m2m'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productvideo',
            new_name='products_pr_process_a49781_idx',
            old_name='pv_processing_status_idx',
        ),
        migrations.RenameIndex(
            model_name='productvideo',
            new_name='products_pr_show_in_050ac9_idx',
            old_name='pv_show_in_gallery_idx',
        ),
        migrations.RenameIndex(
            model_name='productvideo',
            new_name='products_pr_is_feat_e9a60e_idx',
            old_name='pv_is_featured_idx',
        ),
    ]
