# Generated by Django 5.1.15 on 2026-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_pv_processing_status_idx_products_pr_process_a49781_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='خودکار تولید می\u200cشود: IR{comb}-{random}', max_length=20, verbose_name='کد محصول (SKU)'),
        ),
    ]
