# Generated by Django 5.1.15 on 2026-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='خودکار تولید می\u200cشود: IR{comb}-{random}', max_length=20, unique=True, verbose_name='کد محصول (SKU)'),
        ),
    ]
