# Generated by Django 5.1.15 on 2026-04-29 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='UUID برای تفکیک آپلودهای مختلف', max_length=64, verbose_name='کلید سشن')),
                ('file', models.ImageField(upload_to='products/temp/', verbose_name='فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر شاخص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_uploads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آپلود موقت',
                'verbose_name_plural': 'آپلودهای موقت',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
