# Generated by custom script

from django.db import migrations


def delete_old_videos(apps, schema_editor):
    """حذف ویدیوهای قدیمی قبل از migration"""
    ProductVideo = apps.get_model('products', 'ProductVideo')
    count = ProductVideo.objects.count()
    if count > 0:
        print(f"حذف {count} ویدیوی قدیمی...")
        ProductVideo.objects.all().delete()
        print("ویدیوهای قدیمی حذف شدند")
    else:
        print("ویدیوی قدیمی وجود ندارد")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),  # آخرین migration را اینجا قرار دهید
    ]

    operations = [
        migrations.RunPython(delete_old_videos, migrations.RunPython.noop),
    ]
